channels:
  - bioconda
  - conda-forge
dependencies:
  - snakemake-minimal >=7.18.2
  - bcftools =1.16
  - samtools =1.16
  - calitas =1.0
  - crispritz =2.6.6
  - seqkit =2.3.1
  - java-jdk =8.0.112
